source 'https://github.com/CocoaPods/Specs.git'

target 'Example', :exclusive => true do
  pod 'UIViewController+ChildControllers', :path => '../'
end

target 'Tests', :exclusive => true do
  pod 'UIViewController+ChildControllers', :path => '../'
end
