source 'https://github.com/CocoaPods/Specs.git'

target 'ChildControllers', :exclusive => true do
  pod "UIViewController+ChildControllers", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "UIViewController+ChildControllers", :path => "../"

  
end
